spring:
  application.name: bike_rental_api

  profiles:
    include: oauth

  datasource:
    url: jdbc:mariadb://localhost:3306/bikerental
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 51295227107-hpf972btv4fmbevv747ia6es7l0p55fg.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope: ["profile", "email"]
          naver:
            client-id: rKK4ACyKITRSh079e9jv
            client-secret: MRQqJksWSQ
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: name,email
            client-name: Naver
          kakao:
            client-id: 5cd595b69d1193bda78df1a57dd21314
            client-secret: VQWo8LIb22uq5CouGKcYZAFMewADNgYb
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver ?? ? resultCode, message, response ? response ??
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao ?? ? id, connected_at, properties, kakao_account ? id ??
logging:
  level:
    org:
      springframework:
        security: DEBUG

#redis.host: localhost
#redis.port: 6379
#jpa.hibernate.ddl-auto: update
#jpa.show-sql: true
jwt.secret: 8A395AD1543AC4FFA99ADA4EFD4AA21FA1BFDEF32DF51B6BD2C222F48B43883F
jwt.expiration: 3600000

sns.google.url: https://accounts.google.com/o/oauth2/v2/auth
sns.google.client.id: 51295227107-hpf972btv4fmbevv747ia6es7l0p55fg.apps.googleusercontent.com
sns.google.client.secret: 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
sns.google.callback.url: http://localhost:8080/login/oauth2/code/google
sns.google.token.url: https://oauth2.googleapis.com/token

